module_params:
  decoder_width: 1024
  decoder_depth: 4
  attribute_nn_width: 512
  attribute_nn_depth: 2
  n_latent_attribute_categorical: 4
  gene_likelihood: "normal"
  reconstruction_penalty: 1e2
  unknown_attribute_penalty: 1e1
  unknown_attribute_noise_param: 1e-1
  attribute_dropout_rate: 0.1
  use_batch_norm: false
  use_layer_norm: false

# model
model:
  n_latent: 32

# trainer
trainer:
  n_epochs_warmup: 0
  latent_lr: 1e-4
  latent_wd: 1e-4
  decoder_lr: 1e-4
  decoder_wd: 1e-4
  attribute_nn_lr: 1e-2
  attribute_nn_wd: 4e-8
  step_size_lr: 45
  cosine_scheduler: true
  scheduler_final_lr: 1e-5
  batch_size: 512
