type: CB_VAE
has_cbm: True
lr: 1e-3
beta: 1e-5
hidden_dim: 128
latent_dim: 64
min_bottleneck_size: 32
independent_training: False
concepts_hp: 0.005
orthogonality_hp: 0.5
n_decoder_layers: 2
scale_concept: False
use_soft_concepts: False
