type: SCBM
has_cbm: True
lr: 5e-4
beta: 1e-5
input_dim: 5000
hidden_dim: 128
latent_dim: 64
n_concepts: 8
min_bottleneck_size: 32
independent_training: False
concepts_hp: 0.005
orthogonality_hp: 0.1
n_unknown: 32
early_stopping: False
use_orthogonality_loss: True
amortized: False
