type: SKIP_SINGLE_CB_VAE
has_cbm: True
lr: 0.000500
beta: 0.000010
input_dim: 5000
hidden_dim: 256
latent_dim: 64
n_concepts: 8
min_bottleneck_size: 128
concepts_hp: 0.005
normalize: True
orthogonality_hp: 0.2
n_decoder_layers: 2
scale_concept: False
use_soft_concepts: False
independent_training: True
