_target_: conceptlab.models.cb_vae.CBM_MetaTrainer
concept_key: ${data.concept_key}
max_epochs: 200
log_every_n_steps: 10
num_workers: 4
obsm_key: X
z_score: False
cbm_config:
  n_unknown: 128
  lr: 5e-4
  beta: 1e-4
  n_layers: 2
  concepts_hp: 0.05
  hidden_dim: 128
  min_bottleneck_size: 128
  latent_dim: 128
  orthogonality_hp: 0.5
  decoder_type: 'skip'
  use_soft_concepts: False
