_target_: conceptlab.models.cb_fm.CBMFM_MetaTrainer
emb_dim: 1024
n_layers: 6
num_epochs: 1000
batch_size: 128
lr: 3e-4
p_drop: 0.1
raw: False
concept_key: ${data.concept_key}
cbm_mod:
  _target_: conceptlab.models.cb_vae.CBM_MetaTrainer
  concept_key: ${data.concept_key}
  max_epochs: 200
  log_every_n_steps: 10
  cbm_config:
    has_cbm: True
    lr: 5e-4
    hidden_dim: 256
    beta: 1e-5
    latent_dim: 128
    min_bottleneck_size: 128
    independent_training: True
    concepts_hp: 0.005
    orthogonality_hp: 0.2
    use_soft_concepts: False
