_target_: conceptlab.models.cb_vae.Mixed_CBM_MetaTrainer
concept_key: ${data.concept_key}
max_epochs: 200
log_every_n_steps: 10
num_workers: 4
obsm_key: X_pca
z_score: False
cbm_config:
  has_cbm: True
  lr: 3e-4
  n_layers: 4
  hidden_dim: 1024
  beta: 1e-5
  latent_dim: 128
  n_unknown: 128
  min_bottleneck_size: 128
  #independent_training: True
  concepts_hp: 0.1
  orthogonality_hp: 0.5
soft_concept_key: ${data.soft_concept_key}
hard_concept_key: ${data.hard_concept_key}
