_target_: conceptlab.models.sc_cvae.CVAE_MetaTrainer
concept_key: ${data.concept_key}
max_epochs: 200
log_every_n_steps: 10
num_workers: 4
obsm_key: X_pca
z_score: False
cvae_config:
  lr: 3e-4
  n_layers: 4
  hidden_dim: 1024
  beta: 1e-5
  latent_dim: 128
  dropout: 0.0
