_target_: conceptlab.models.trvae.trVAE
concept_key: ${data.concept_key}
concepts_to_flip: ${data.intervention_labels.concepts_to_flip}
concepts_as_cov: ${data.concepts_as_cov}
concepts_to_flip_ref: ${data.intervention_labels.reference}
target_sum: ${data.target_sum}
