_decoder: !!python/name:conceptlab.models.decoder.SkipDecoderBlock ''
_encoder: !!python/name:conceptlab.models.encoder.DefaultEncoderBlock ''
config:
  beta: 1.0e-05
  concepts_hp: 0.005
  has_cbm: true
  hidden_dim: 128
  independent_training: true
  input_dim: 9653
  latent_dim: 64
  lr: 0.0005
  min_bottleneck_size: 8
  n_concepts: 86
  orthogonality_hp: 1
  use_soft_concepts: true
