type: CB_VAE

input_dim: null
n_concepts: null


has_cbm: True
lr: 0.0005
beta: 0.00001
hidden_dim: 256
latent_dim: 64
min_bottleneck_size: 64
concepts_hp: 0.005
normalize: True
orthogonality_hp: 0.2
n_decoder_layers: 2
independent_training: True
