type: CEM_VAE

input_dim: null
n_concepts: null

has_cbm: True
lr: 0.000500
beta: 0.000100
hidden_dim: 256
latent_dim: 128
min_bottleneck_size: 128
concepts_hp: 0.005
normalize: True
orthogonality_hp: 0.2
n_decoder_layers: 2
independent_training: True
