type: scCEM

input_dim: null
n_concepts: null

has_cbm: True
lr: 5e-4
beta: 1e-4
n_layers: 2
concepts_hp: 0.1
hidden_dim: 128
min_bottleneck_size: 128
latent_dim: 64
orthogonality_hp: 0.2
decoder_type: 'skip'
