type: scCBGM

input_dim: null
n_concepts: null

has_cbm: True
lr: 5e-4
n_layers: 2
hidden_dim: 256
beta: 1e-05
latent_dim: 128
n_unknown: 128
min_bottleneck_size: 128
# independent_training: True
concepts_hp: 0.005
orthogonality_hp: 0.2
use_soft_concepts: False
