# made to be equivalent to scCBGM - used in ablation
type: scCEM

input_dim: null
n_concepts: null

has_cbm: True
n_unknown: 128
lr: 5e-4
beta: 1e-4
n_layers: 2
concepts_hp: 0.05
hidden_dim: 128
min_bottleneck_size: 128
latent_dim: 128
orthogonality_hp: 0.5
decoder_type: 'no residual'
use_soft_concepts: False
use_cosine_loss: True
