_decoder: !!python/name:conceptlab.models.decoder.SkipDecoderBlock ''
_encoder: !!python/name:conceptlab.models.encoder.DefaultEncoderBlock ''
config:
  beta: 1.0e-05
  concepts_hp: 0.005
  has_cbm: true
  hidden_dim: 256
  independent_training: true
  input_dim: 9224
  latent_dim: 128
  lr: 0.0005
  min_bottleneck_size: 128
  n_concepts: 9
  orthogonality_hp: 0.2
  use_soft_concepts: false
